[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = ["dotnet publish -c Release -o out"]

[phases.start]
cmd = "cd out && dotnet spotifyClone.dll"

[variables]
ASPNETCORE_ENVIRONMENT = "Production"
